<a href="https://colab.research.google.com/github/hasanyusuf01/Codes/blob/main/phyaat2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install phyaat

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm

#!pip install phyaat  # if not installed yet
import phyaat
print('Version :' ,phyaat.__version__)
import phyaat as ph

Version : 0.0.3


In [ ]:
# Download dataset of one subject only (subject=1)
# To download data of all the subjects use subject =-1 or for specify for one e.g.subject=10

dirPath = ph.download_data(baseDir='../PhyAAt_Data', subject=1,verbose=0,overwrite=False)

baseDir='../PhyAAt_Data'   # or dirPath return path from above

#returns a dictionary containing file names of all the subjects available in baseDir
SubID = ph.ReadFilesPath(baseDir)

#check files of subject=1
print(SubID[1])

 # Create a Subj holding dataset of subject=1
Subj = ph.Subject(SubID[1])


#filtering with highpass filter of cutoff frequency 0.5Hz
Subj.filter_EEG(band =[0.5],btype='highpass',order=5)

Total Subjects :  1
{'sigFile': '../PhyAAt_Data/phyaat_dataset/Signals/S1/S1_Signals.csv', 'txtFile': '../PhyAAt_Data/phyaat_dataset/Signals/S1/S1_Textscore.csv'}


In [ ]:
# Extract Rhythmic features for task=4
X_train,y_train,X_test, y_test = Subj.getXy_eeg(task=4)


print('DataShape: ',X_train.shape,y_train.shape,X_test.shape, y_test.shape)
print('\nClass labels :',np.unique(y_train))

# Normalization - SVM works well with normalized features









DataShape:  (290, 84) (290,) (120, 84) (120,)

Class labels : [0 1 2]


In [ ]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2])

In [ ]:
X_train

array([[2.49485493, 2.12746824, 1.60700632, ..., 0.05104358, 0.03586729,
        0.0353022 ],
       [2.65408715, 2.26533739, 1.96172614, ..., 0.03362956, 0.03442574,
        0.03756099],
       [2.52234749, 2.59840008, 2.17089983, ..., 0.09018123, 0.0568996 ,
        0.059435  ],
       ...,
       [1.84866726, 1.74081858, 1.0978413 , ..., 0.00316687, 0.01839323,
        0.01688799],
       [1.24819335, 1.15641392, 0.65469111, ..., 0.01273232, 0.02964069,
        0.01696939],
       [0.16094742, 0.12859839, 0.05236514, ..., 0.00931242, 0.02606447,
        0.01410056]])

In [ ]:
means = X_train.mean(0)
std   = X_train.std(0)
X_train = (X_train-means)/std
X_test  = (X_test-means)/std

In [ ]:
X_train

array([[ 4.75730274e-01,  2.37394777e-01, -1.96838685e-03, ...,
         1.02065680e+00, -4.11479922e-01, -4.51019101e-01],
       [ 6.97314122e-01,  4.38910979e-01,  5.44568868e-01, ...,
         2.01942674e-01, -4.75264404e-01, -3.65072298e-01],
       [ 5.13988285e-01,  9.25731481e-01,  8.66854809e-01, ...,
         2.86070017e+00,  5.19137438e-01,  4.67231529e-01],
       ...,
       [-4.23489424e-01, -3.27751035e-01, -7.86468252e-01, ...,
        -1.23025018e+00, -1.18465520e+00, -1.15167826e+00],
       [-1.25909493e+00, -1.18194511e+00, -1.46925527e+00, ...,
        -7.80533711e-01, -6.86988580e-01, -1.14858101e+00],
       [-2.77208104e+00, -2.68424991e+00, -2.39729357e+00, ...,
        -9.41319385e-01, -8.45225420e-01, -1.25773949e+00]])

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:

# Training
clf = svm.SVC(kernel='rbf', C=1,gamma='auto')
clf.fit(X_train,y_train)

# Predition
ytp = clf.predict(X_train)
ysp = clf.predict(X_test)

# Evaluation

print('Training Accuracy:',np.mean(y_train==ytp))
print('Testing  Accuracy:',np.mean(y_test==ysp))


Training Accuracy: 0.9310344827586207
Testing  Accuracy: 0.8666666666666667
